[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[functions]]
  path = "/parse-tribal"
  schedule = ""
  timeout = 60

[[functions]]
  path = "/parse-vibrant"
  schedule = ""
  timeout = 60

[[functions]]
  path = "/product-lookup"
  schedule = ""
  timeout = 15
