[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."parse-vibrant"]
  timeout = 120

[functions."product-lookup"]
  timeout = 15

[functions."parse-tribal"]
  timeout = 120
